### ISSUE TITLE
[Feat] Adding Services for the API  

### ISSUE THREAD

**Issue by JuancaSalaG** [C10-Ghibli-s/BE-Studio-Ghibli-Tracker#13]
### Summary 🗂
Create the services in order to give functionality to the users and movies module and implement entities for the data integrity.
### Acceptance Criteria
- [x] Create the service for users module
- [x] Create the service for movies module
- [x] Modeling the users entity
- [x] Modeling the movies entity

**Comment by LifeSpaceJuan** [comment]
The implementation of services in users and movies module is done. Also, the creation of entities of a user object and movie object in order to control the dev environment is already added.

**Comment by LifeSpaceJuan** [comment]
:smile:
